# Generated by Django 5.2.6 on 2025-12-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatalog', '0001_initial'),
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfileupload',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='datacatalog.category'),
        ),
    ]
