# Generated by Django 5.2.6 on 2025-12-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_full_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_phone', models.CharField(max_length=20)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(blank=True, max_length=100)),
                ('organization_address', models.TextField(blank=True)),
                ('motivation', models.TextField()),
                ('official_letter', models.FileField(upload_to='access_requests/letters/')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='access_requests/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
